name: php_images
on:
  push:
    branches:
      - master

env:
  HUB_USERNAME: ${{ vars.HUB_USERNAME }}
  REGISTRY: docker.io
  DOCKER_IMAGE: php

jobs:
  build:
    strategy:
      matrix:
        php_version: [8.2, 8.3]
        tag: [cli, sql]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v2
        with:
          use: true
          driver: remote
          endpoint: tcp://amd64.${{ secrets.BUILDKIT_HOST }}:443
          platforms: linux/amd64
          append: |
            - endpoint: tcp://arm64.${{ secrets.BUILDKIT_HOST }}:443
              driver: remote
              platforms: linux/arm64
        env:
          BUILDER_NODE_0_AUTH_TLS_CACERT: ${{ secrets.DOCKER_TLS_CA }}
          BUILDER_NODE_0_AUTH_TLS_CERT: ${{ secrets.DOCKER_TLS_CERT }}
          BUILDER_NODE_0_AUTH_TLS_KEY: ${{ secrets.DOCKER_TLS_KEY }}
          BUILDER_NODE_1_AUTH_TLS_CACERT: ${{ secrets.DOCKER_TLS_CA }}
          BUILDER_NODE_1_AUTH_TLS_CERT: ${{ secrets.DOCKER_TLS_CERT }}
          BUILDER_NODE_1_AUTH_TLS_KEY: ${{ secrets.DOCKER_TLS_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and push base SQL
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          target: base
          file: ./php/${{ matrix.php_version }}/${{ matrix.tag }}.dockerfile
          tags: ${{ env.HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ matrix.php_version }}-${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push base SQL dev
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          target: dev
          file: ./php/${{ matrix.php_version }}/${{ matrix.tag }}.dockerfile
          tags: ${{ env.HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ matrix.php_version }}-${{ matrix.tag }}-dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
